version: '3.1'

services:
  bot:
    image: node:14.9.0
    restart: always
    command: npm run start
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      MYSQL_HOST: mysql
      RESPOND_TO_BOT_MESSAGES: ${RESPOND_TO_BOT_MESSAGES}
      RESPOND_TO_BOT_REACTIONS: ${RESPOND_TO_BOT_REACTIONS}
  mysql:
    image: mariadb
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql

