version: '3.1'

services:
  bot:
    image: node:14.9.0
    restart: always
    command: npm run start
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    env_file: .env
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql
  mysql:
    image: mariadb
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      
